framework:
    secret: '%env(APP_SECRET)%'

    session: true

    trusted_proxies: '127.0.0.1'
    trusted_headers: [ "X-Forwarded-Proto" ]

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
